	$(document).ready(function () {
	    var quoteBank = [{
	            quote: "A typical rocket produces more than a million pounds of thrust that allows it to carry more than 6,000 pounds at speeds topping 22,000 miles per hour. This is equivalent to the power generated by 13 Hoover Dams, carrying the weight of eight horses, and traveling at speeds 15 times faster than a speeding bullet!"
	        },
	        {
	            quote: "Robert Goddard is considered the father of modern rocketry. He built the first liquid-fueled rocket in 1926. The rocket climbed 12 meters in 2.5 seconds."
	        },
	        {
	            quote: "A typical rocket produces more than a million pounds of thrust. They can travel at 22,000 miles per hour carrying 6,000 pounds!"
	        },
	        {
	            quote: "Launch rockets are actually several rockets linked together. When one rocket expends all of its fuel, it breaks apart and falls away, making the unit lighter to travel faster."
	        },
	        {
	            quote: "The fastest rocket record was set by the Atlas V in 2006. It left the atmosphere traveling 36,000 miles per hour and topped out at 47,000 miles per hour."
	        },
	        {
	            quote: "You may have heard of the modern company SpaceX. They are working to make rockets that can be used multiple times, which will make space travel much easier. So far they have managed to land an unmanned rocket back on a launch pad on land, and are working on making it land on a pad at sea."
	        },
	        {
	            quote: "The Falcon Heavy rocket lifted off for the first time on Feb. 6, 2018, from Kennedy Space Center (KSC) in Cape Canaveral, Florida, using Launch Complex 39A, the pad that used to host moon-bound Apollo astronauts and space shuttle crews. "
	        },
	        {
	            quote: "The first development of rockets was by the Chinese in 1232 AD, when they used gunpowder projectiles in battle. However, there is evidence that suggests they were experimenting with these prototypical rockets as far back as 995 AD."
	        },
	        {
	            quote: "The use of metallic cylinder rocket artillery came along in 1792, when the rulers of Mysore in India developed the technology. After they were defeated by the British, the British took these developments and expanded them further into the 19th century."
	        },
	        {
	            quote: "JPL maintained operations after Parsons’ death, and after developing the Explorer 1 satellite, which commenced America’s entry into the Space Race with the Soviet Union, it was integrated into the National Aeronautics and Space Administration."
	        },
	        {
	            quote: "Explorer 1 was sent into space in 1958, and remained there until 1970. It had a mass of only 13.37 kilograms. This weight was very light compared to the Soviets’ first satellite, Sputnik, which was 83.6 kg. Explorer was fitted with a Cosmic-ray detector and a Micrometeorite detector."
	        },
	        {
	            quote: "In order to be able to burst through the gravity of the Earth, a rocket needs to travel at a speed of 7 miles per second. Now, we’re not scientists ourselves, but it seems like that’s pretty fast."
	        },
	        {
	            quote: "Sputnik 1 preceded the launch of Explorer 1, and the Soviets actually got off a second rocket, the Sputnik 2, before the Americans achieved success with Explorer 1. Sputnik was originally launched on October 4th, 1957, and was a spherical object fitted with antennas, as opposed to the cylindrical shape of the Explorer."
	        },
	        {
	            quote: "The Soviets launched Sputnik 2 only two months after Sputnik 1, but this time it carried a small dog by the name of Laika. Laika would become the first animal to orbit Earth, but wouldn’t last very long, as she died shortly afterward. Some scientists were skeptical about a human’s ability to survive a launch, so animals were tested first. Because our lives matter more, of course."
	        },
	        {
	            quote: "The Space Race got its start when Mstislav Kaldysh, Sergey Korolyov, and Mikhail Tikhonravov submitted a letter to the Soviet government proposing the development of an artificial satellite to orbit the Earth."
	        },
	        {
	            quote: "Robert H. Goddard is also sometimes considered the father of modern rocket science, as the scientist first flew a liquid propellant rocket in 1926, which turned out to be the progenitor of the Saturn V rocket that launched 43 years later."
	        },
	        {
	            quote: "In 1881, the history of rocket propulsion took an odd turn when Nikolai Ivanovich Kibalchich, one of Russia’s rocket pioneers, took part in the assassination of Tsar Alexander II. As the main explosive expert, Kibalchich shot four projectiles at the Tsar and killed him. The 27-year-old genius would be arrested and executed, but was still hard at work on mathematical equations while he sat in prison."
	        }

	    ];

	    $('#hitMe').click(function (evt) {
	        var quote = $('#rocketFact p').text();
	        evt.preventDefault();
	        var sourceBankLength = quoteBank.length;
	        var randomNumber = Math.floor(Math.random() * sourceBankLength);
	        for (i = 0; i <= sourceBankLength; i += 1) {
	            var newRocketFact = quoteBank[randomNumber].quote;
	            var timeAnimation = 250;
	            var rocketFact = $('#rocketFact');
	            rocketFact.fadeOut(timeAnimation, function () {
	                rocketFact.html('');
	                rocketFact.append('<p>' + newRocketFact + '</p>');
	                rocketFact.fadeIn(timeAnimation);
	            });
	            break;
	        };
	    });
	});